#!/usr/bin/env python3
"""
Generate game/.gitattributes (the first-commit Git LFS manifest) from
tools/inventory.yaml.

Routing:
  * binary lumps  -> Git LFS (filter=lfs ... -text)
  * text lumps    -> NO rule => normal git, stored byte-for-byte (no EOL
                     normalization) and diffable.

Binary files that have an extension are covered by a single glob per extension
(safe: every extension in this tree is uniformly one type, verified separately).
Extensionless binaries are pinned by exact path; paths containing spaces are
double-quoted (the only encoding git's attribute parser accepts for them).

This manifest is deliberately exhaustive/throwaway: it exists to get a faithful
first commit. After we rename extensionless lumps to real extensions, regenerate
and it collapses to pure extension rules.

Usage: python3 tools/gen_gitattributes.py
"""
import os
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
LFS = "filter=lfs diff=lfs merge=lfs -text"
TEXT_TYPES = {"text", "empty"}
SAFE = set("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789/._-")


def quote(path: str) -> str:
    """Bare path if safe, else a git C-quoted string (handles spaces)."""
    if all(c in SAFE for c in path):
        return path
    esc = path.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{esc}"'


def main():
    inv = yaml.safe_load(open(REPO / "tools" / "inventory.yaml"))
    bin_exts = {}
    extensionless = []
    n_text = 0

    for f in inv["files"]:
        if f["type"] in TEXT_TYPES:
            n_text += 1
            continue
        ext = os.path.splitext(f["path"])[1]  # case-preserved (don't trust lowercased field)
        if ext:
            bin_exts[ext] = bin_exts.get(ext, 0) + 1
        else:
            extensionless.append(f["path"])

    lines = [
        "# AUTO-GENERATED by tools/gen_gitattributes.py from tools/inventory.yaml",
        "# First-commit Git LFS manifest for the mod tree (game/).",
        "# Binary lumps -> Git LFS. Text lumps are intentionally unlisted => normal",
        "# git, stored byte-for-byte (no EOL normalization) and fully diffable.",
        "# Regenerate after any rename: python3 tools/gen_gitattributes.py",
        "",
        "# --- binary, by extension (each extension verified uniformly binary) ---",
    ]
    for ext in sorted(bin_exts):
        lines.append(f"*{ext} {LFS}")
    lines += [
        "",
        f"# --- binary, extensionless ({len(extensionless)} lumps), pinned by exact path ---",
    ]
    for p in sorted(extensionless):
        lines.append(f"{quote(p)} {LFS}")

    out = REPO / "game" / ".gitattributes"
    out.write_text("\n".join(lines) + "\n")

    print(f"wrote {out}")
    print(f"  binary extension globs : {len(bin_exts):>4}  ->  {sum(bin_exts.values())} files")
    print(f"  extensionless binaries : {len(extensionless):>4}  (exact-path rules)")
    print(f"  text files (no rule)   : {n_text:>4}  (normal git)")
    print(f"  TOTAL -> LFS           : {sum(bin_exts.values()) + len(extensionless)}")
    print(f"  globbed extensions     : {', '.join(sorted(bin_exts))}")


if __name__ == "__main__":
    main()
